# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(249, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ukpur = QtWidgets.QRadioButton(self.centralwidget)
        self.ukpur.setGeometry(QtCore.QRect(0, 83, 114, 21))
        self.ukpur.setObjectName("ukpur")
        self.uiur = QtWidgets.QRadioButton(self.centralwidget)
        self.uiur.setGeometry(QtCore.QRect(20, 60, 114, 24))
        self.uiur.setObjectName("uiur")
        self.updi = QtWidgets.QRadioButton(self.centralwidget)
        self.updi.setGeometry(QtCore.QRect(40, 40, 114, 24))
        self.updi.setObjectName("updi")
        self.iudr = QtWidgets.QRadioButton(self.centralwidget)
        self.iudr.setGeometry(QtCore.QRect(140, 40, 114, 24))
        self.iudr.setObjectName("iudr")
        self.ipdu = QtWidgets.QRadioButton(self.centralwidget)
        self.ipdu.setGeometry(QtCore.QRect(160, 60, 114, 24))
        self.ipdu.setObjectName("ipdu")
        self.ikpdr = QtWidgets.QRadioButton(self.centralwidget)
        self.ikpdr.setGeometry(QtCore.QRect(180, 80, 114, 24))
        self.ikpdr.setObjectName("ikpdr")
        self.puui = QtWidgets.QRadioButton(self.centralwidget)
        self.puui.setGeometry(QtCore.QRect(0, 120, 114, 24))
        self.puui.setObjectName("puui")
        self.pi2ur = QtWidgets.QRadioButton(self.centralwidget)
        self.pi2ur.setGeometry(QtCore.QRect(30, 140, 114, 24))
        self.pi2ur.setObjectName("pi2ur")
        self.pu2dr = QtWidgets.QRadioButton(self.centralwidget)
        self.pu2dr.setGeometry(QtCore.QRect(50, 160, 114, 24))
        self.pu2dr.setObjectName("pu2dr")
        self.ru2dp = QtWidgets.QRadioButton(self.centralwidget)
        self.ru2dp.setGeometry(QtCore.QRect(180, 120, 114, 24))
        self.ru2dp.setObjectName("ru2dp")
        self.rudi = QtWidgets.QRadioButton(self.centralwidget)
        self.rudi.setGeometry(QtCore.QRect(160, 140, 114, 24))
        self.rudi.setObjectName("rudi")
        self.rpdi2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rpdi2.setGeometry(QtCore.QRect(140, 160, 114, 24))
        self.rpdi2.setObjectName("rpdi2")
        self.uText = QtWidgets.QLineEdit(self.centralwidget)
        self.uText.setGeometry(QtCore.QRect(40, 200, 181, 36))
        self.uText.setObjectName("uText")
        self.iText = QtWidgets.QLineEdit(self.centralwidget)
        self.iText.setGeometry(QtCore.QRect(40, 230, 181, 31))
        self.iText.setObjectName("iText")
        self.rText = QtWidgets.QLineEdit(self.centralwidget)
        self.rText.setGeometry(QtCore.QRect(40, 260, 181, 31))
        self.rText.setObjectName("rText")
        self.pText = QtWidgets.QLineEdit(self.centralwidget)
        self.pText.setGeometry(QtCore.QRect(40, 290, 181, 31))
        self.pText.setObjectName("pText")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 350, 103, 36))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ukpur.setText(_translate("MainWindow", "√P*R"))
        self.uiur.setText(_translate("MainWindow", "I*R"))
        self.updi.setText(_translate("MainWindow", "P/I"))
        self.iudr.setText(_translate("MainWindow", "U/R"))
        self.ipdu.setText(_translate("MainWindow", "P/U"))
        self.ikpdr.setText(_translate("MainWindow", "√P/R"))
        self.puui.setText(_translate("MainWindow", "U*I"))
        self.pi2ur.setText(_translate("MainWindow", "I^2*R"))
        self.pu2dr.setText(_translate("MainWindow", "U^2/R"))
        self.ru2dp.setText(_translate("MainWindow", "U^2/P"))
        self.rudi.setText(_translate("MainWindow", "U/I"))
        self.rpdi2.setText(_translate("MainWindow", "P/I^2"))
        self.pushButton.setText(_translate("MainWindow", "Go"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
